# Generated by Django 3.2.15 on 2023-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_APP', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(null=True),
        ),
    ]
