# Generated by Django 4.1.5 on 2023-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_APP', '0006_auto_20230327_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(help_text='Price Per Day', null=True),
        ),
    ]
