# Generated by Django 4.1.5 on 2023-03-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_APP', '0007_alter_room_room_picture_alter_room_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS_APP.booking'),
        ),
    ]
