# Generated by Django 4.1.5 on 2023-03-28 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HMS_APP', '0009_bookinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='check_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS_APP.room'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
